spring:
# jackson:
#   serialization:
#     indent-output: true
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy    
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
  datasource:
    driver-class-name: org.postgresql.Driver

  data:
    jpa:
      repositories:
        enabled: true
        
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 
    