spring:
# jackson:
#   serialization:
#     indent-output: true
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy    
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
  datasource:
    driver-class-name: org.postgresql.Driver
 #  url: jdbc:postgresql://202.99.114.136:10012/testacti
    url: jdbc:postgresql://202.99.114.136:10012/spbtestred  # test
 #  url: jdbc:postgresql://202.99.114.136:10018/ceserver  # using
 #  url: jdbc:postgresql://192.168.60.23:3080/ceserver    # inner net using
 #  url: jdbc:postgresql://127.0.0.1:3080/ceserver
 #  url: jdbc:postgresql://127.0.0.1:3080/testacti
 #  url: jdbc:postgresql://127.0.0.1:3080/ceserver
    username: postgres
    password: tvpgsql135
  data:
    jpa:
      repositories:
        enabled: true
        
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 
    